### ISSUE TITLE
Can't download from Funimation

### ISSUE THREAD

**Issue by Azul772** [hama3254/Crunchyroll-Downloader-v3.0#102]
Crunchyroll Downloader 3.6.2
<img width="1920" alt="error 30" src="https://user-images.githubusercontent.com/75436296/101378962-18f0ab00-388a-11eb-8c0f-6eb9166cc395.png">

I can't download anything from Funimation, I always get the above message.

**Comment by hama3254** [comment]
There seems to be a problem with the naming function as your error message indicates but i get another problem than you with v3.6.3
Please share the add window so i can see what part of the code might be the cause. 
for reference i just have a missing `\` in my version (v3.6.3) which results in the wrong path.
(just ignore the dark theme for now, this is a slightly changed test version)  
![grafik](https://user-images.githubusercontent.com/52826614/101385156-aef0f980-38bb-11eb-95e6-bf49ac7caa26.png)

**Comment by Azul772** [comment]
<img width="525" alt="add" src="https://user-images.githubusercontent.com/75436296/101388819-da152200-3896-11eb-8fec-e2d902d638a6.png">

**Comment by hama3254** [comment]
That looks fine, despite the folder issues with funimation i can not see why there should be an illegal character in the path. 
Sure the Episodes all contains `-` but that works for me as character for names.
You could try to create a textfile with the name `GARO THE ANIMATION Season 1 Episode 1 -HELL FIRE-` maybe there is a difference with other windows languages.

**Comment by Azul772** [comment]
What do you mean by create a textfile?

**Comment by hama3254** [comment]
never mind, i thought maybe the English Windows 10 version has other encoding options that my German one but i just downloaded a Windows 10 Pro 20H2 in the US English version and well it just works as intended (except the known issues which are fixed but release come not before the weekend)
![grafik](https://user-images.githubusercontent.com/52826614/101396993-60982680-38cc-11eb-9f99-e175a98aa616.png)
 
The only thing i can do for you is to suggest to change the name setting to episode number in the output settings 


![grafik](https://user-images.githubusercontent.com/52826614/101397584-2aa77200-38cd-11eb-8fbb-b2ce6cb2a996.png)

**Comment by Azul772** [comment]
I tried changing the naming to just the episode number and this is what happened:
<img width="1920" alt="error add 2" src="https://user-images.githubusercontent.com/75436296/101398622-c1ac0400-38a4-11eb-8404-71d4e269fd21.png">

I still can't download the Garo series from funimation.

**Comment by hama3254** [comment]
I'm sorry but i have to ask, did you saved the settings before trying to download the episode(s)?

**Comment by Azul772** [comment]
yes

**Comment by hama3254** [comment]
then i'm clueless where the issue comes from so the only idea i have left to solve the issue is to either disable the subtitles then it should work since that is the only file access in the funimation function so we see the name that get's added to the download process.

**Comment by Azul772** [comment]
The hard subtitles were the problem, here is the proof
<img width="1137" alt="error 50" src="https://user-images.githubusercontent.com/75436296/101404904-a691c200-38ad-11eb-8709-3406268a47da.png">

How can I fix this so I don't have the subtitles in a separate file?

**Comment by hama3254** [comment]
in the output settings is a option to merge the mp4 file with the subtitle files, it it still soft sub but it's just one mp4 at the end.
Thanks for your help i take a look at it tomorrow it's to late now for me.

**Comment by Azul772** [comment]
Would merging the video and subtitles this way be any different from hard subtitles initially?

**Comment by Azul772** [comment]
I checked the merge with soft-subtitles sub box and this was the result:
<img width="1365" alt="error s" src="https://user-images.githubusercontent.com/75436296/101407596-7e0bc700-38b1-11eb-93e8-0f7dcbddd30c.png">

Now the download crashes immediately.

**Comment by hama3254** [comment]
You can try this new version : https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.6.4

**Comment by Azul772** [comment]
The new version, 3.6.4, was able to download the video and subtitles without me having to choose the merge-sub option. It turned out great. Thank you.
<img width="1920" alt="solved" src="https://user-images.githubusercontent.com/75436296/101533182-e4edb680-396b-11eb-921b-723fac218f9d.png">

**Comment by hama3254** [comment]
Nice to hear that it works, I guess I can close this now.
If you have any new questions or issues just open a new issue.
